# Generated by Django 2.1 on 2019-07-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190731_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='attachments',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
