# Generated by Django 2.1 on 2019-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190731_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='attachments',
            field=models.TextField(),
        ),
    ]
