# Generated by Django 2.1 on 2019-08-01 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190731_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Users'),
        ),
    ]
