# Generated by Django 2.1 on 2019-08-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assets_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='barcode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
